apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "exim.fullname" . }}
  labels:
    app: {{ .Release.Name }}-wordpress
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mail
spec:
  replicas: {{ .Values.exim.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "exim.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "exim.name" . }}
        release: {{ .Release.Name }}
        component: mail
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.exim.image.repository }}:{{ .Values.exim.image.tag }}"
          imagePullPolicy: {{ .Values.exim.image.pullPolicy }}
          env:
          - name: APP_HOSTNAME
            value: {{ .Values.hostname | quote }}
          - name: EXIM_SMARTHOST
            value: {{ .Values.exim.smarthost | quote }}
          - name: EXIM_MAIL_FROM
            value: {{ .Values.exim.mailFrom | quote }}
          {{- if and .Values.exim.password .Values.exim.password -}}
          - name: EXIM_SMARTHOST_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-exim"
                key: password
          - name: EXIM_SMARTHOST_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-exim"
                key: username
          {{- end }}
          {{- if .Values.exim.healthProbes }}
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- end }}
          ports:
            - name: smtp
              containerPort: {{ .Values.exim.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.exim.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: release
                operator: NotIn
                values:
                - {{ .Release.Name }}
              - key: component
                operator: NotIn
                values:
                - mail
          - weight: 1
            preference:
              matchExpressions:
              - key: release
                operator: In
                values:
                - {{ .Release.Name }}
              - key: component
                operator: In
                values:
                - php
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
